apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: api-respond
spec:
  args:
  - name: service-name
  metrics:
  - name: api-respond
    interval: 10s
    count: 20
    failureLimit: 3
    provider:
      job:
        spec:
          ttlSecondsAfterFinished: 240
          activeDeadlineSeconds: 220
          backoffLimit: 6
          template:
            spec:
              containers:
              - name: curl-api-test
                image: curlimages/curl:latest
                command: [sh, -c]
                args: ["curl", "-fksSLIw", "%{http_code}", "{{args.service-name}}", "-o", "/dev/null"]
              restartPolicy: OnFailure