apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: api-test
spec:
  args:
  - name: service-name
  metrics:
  - name: api-test
    count: 1
    failureLimit: 1
    provider:
      job:
        spec:
          ttlSecondsAfterFinished: 600
          activeDeadlineSeconds: 220
          backoffLimit: 2
          template:
            spec:
              containers:
              - name: curl-api-test
                image: curlimages/curl:latest
                command:
                - /bin/sh
                - -c 
                - |
                  interval=2
                  iteration=60
                  until curl -fsSI http://localhost:15021/healthz/ready
                  do
                    echo "[ STANDBY ] > Waiting for Sidecar..."
                    sleep 3
                  done
                  echo "[ READY ] > Sidecar available. Running the script..."
                  count=0
                  while [ $count -lt "$iteration" ]
                  do 
                    if [ "$(curl -fksSLIw '%{http_code}' "{{args.service-name}}" -o /dev/null)" = "200" ]
                    then
                      x=$(echo $?)
                      echo "succes code 200"
                      sleep $interval
                      count=$((count+1))
                    else
                      y=$(echo $?)
                      echo "[ FAIL ] > failed curl exit code : $y"
                      exit $y
                    fi
                  done
                  echo "[ SUCCESS ] > Success checking script"
                  curl -fsSI -X POST http://localhost:15020/quitquitquit && exit $x
              restartPolicy: OnFailure