apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: api-respond
spec:
  args:
  - name: service-name
  metrics:
  - name: api-respond
    count: 1
    failureLimit: 1
    provider:
      job:
        spec:
          ttlSecondsAfterFinished: 600
          activeDeadlineSeconds: 220
          backoffLimit: 2
          template:
            spec:
              containers:
              - name: curl-api-test
                image: curlimages/curl:latest
                command: ["/bin/sh", "-c"]
                args: 
                  - |
                    until curl -fsI http://localhost:15021/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 3; done;
                    echo \"Sidecar available. Running the command...\";
                    curl -fksSLIw '%{http_code}' "{{args.service-name}}" -o /dev/null;
                    x=$(echo $?); curl -fsI -X POST http://localhost:15020/quitquitquit && exit $x
              restartPolicy: OnFailure